### ISSUE TITLE
Open to PRs?

### ISSUE THREAD

**Issue by ryanblock** [apexad/node-aladdin-connect-garage-door#11]
Hey there! Thanks for getting this module going, may be something I'd be looking to use. ✨

Right now I'd say a few things could probably use a bit of cleaning up (param signature in the main function, errbacks, async support, etc.), I'm wondering how amenable you are to PRs? (Especially the variety that introduce breaking changes?)

Thanks!

**Comment by apexad** [comment]
Indeed, this was written solely to be used as a home automation helper tool.  Definitely hacked together to be functional first. Currently the best use is done with https://github.com/iAnatoly/homebridge-aladdin-connect-garage-door which was not written by me actually.  However, I have since made contributions to that plugin.

So, on that note, if you do introduce breaking changes that would affect how that project uses this one, I would ask that you make the corrections as a PR there too.  Otherwise I have absolutely no problem with PRs. I might suggest looking into the things I mentioned in the 3 issues first though.

**Comment by apexad** [comment]
One other thing to mention which is extremely important.  I am not a fan of complexity of the code across multiple files if it is not needed.  What I mean by this is that as it stands right now the main code for this plugin is 184 lines which to me is amazingly good. I'd really have to be convinced of a use case to separate logic into other files or something like that in less a lot of functionality was added in the process.

To me, a single file written as concise as possible is easier to understand versus splitting this across multiple files. I hope that makes sense.  I've run into people at work and in the GitHub community that differ in my opinion on this and believe that rather than a single 184 line file, 4 or 5 files with 20-50 lines would be better.

**Comment by ryanblock** [comment]
No worries! Sounds like this works for you and others depend on it, so maybe the more prudent path would be a fork, which you could opt into merging back in as you please. Thanks for the groundwork on this, stoked you got this running!

**Comment by apexad** [comment]
Definitely create a PR for any changes you make so we can talk about them. In thinking about this further I would be fine with making any needed changes as a PR on https://github.com/iAnatoly/homebridge-aladdin-connect-garage-door if you did not want to do that part. I'd have to coordinate with @iAnatoly to make sure both are published around the same time.
